### ISSUE TITLE
Is this possible to show previous 6 months from current month

### ISSUE THREAD

**Issue by imarks-saisudhakar** [MaheshH/jquery-full-year-calendar#1]
Hi Mahesh, 

I am conveying congratulations for this plugin. I modified as per requirement your options such as below

Basic: ['2019-01-01', '2019-01-13','2019-01-03','2019-01-19'],
                            Medium: ['2019-03-25','2019-03-17','2019-03-05'],
                            Avg: ['2018-12-27'],
                            Abvavg: ['2019-03-18','2019-03-20','2018-03-21','2019-03-22','2019-03-23','2019-03-24','2019-03-26','2019-03-28','2019-03-29','2019-03-30']

it works perfectly from current month.
the problem is my dates such as Avg: ['2018-12-27'], the respective month is not showing.

Thanks for your help in advance.

Regards,
Saisudhakar.

**Comment by MaheshH** [comment]
Hi Saisudhakar,

There is an option to start the calendar from a particular month and end it in a particular month.

You can pass yearStart and yearEnd  to the plugin as options, as shown below: 
var fyc = $('#full-year-calendar').fullYearCalendar({
                yearStart: new Date('2018-06-01'),
                yearEnd : new Date('2019-06-01'),
             });

This will make calendar show from June-2018 to June-2019.

**Comment by imarks-saisudhakar** [comment]
Thanks you very much for your Quick response. Feeling Good. It is working fine.
